### ISSUE TITLE
Call to undefined method HisInOneProxy\Soap\Interactions\DataCache::getValueService()

### ISSUE THREAD

**Issue by SeOtte** [DatabayAG/his_in_one_proxy#2]
Bei der Verwendung des Befehls "cm" tritt ein Fehler auf:

PHP Fatal error:  Uncaught Error: Call to undefined method HisInOneProxy\Soap\Interactions\DataCache::getValueService() in [...]/src/System/ConsoleHandler.php:147
Stack trace:
#0 [...]/src/System/ConsoleHandler.php(497): HisInOneProxy\System\ConsoleHandler->getAllCourseMappingTypes(NULL)
#1 [...]/cmd.php(38): HisInOneProxy\System\ConsoleHandler->functionMap('cm', NULL)
#2 [...]/cmd.php(44): HisInOneProxy\Command\startHandler()
#3 {main}
  thrown in [...]/src/System/ConsoleHandler.php on line 147

Hier der Link zur fehlerhaften Zeile:
https://github.com/DatabayAG/his_in_one_proxy/blob/fb7098f7245fe4534f8be66a49c67b682fa7e976/src/System/ConsoleHandler.php#L147

**Comment by gvollbach** [comment]
Disabled in master_2019.06.
Da es keinen ValueService mehr gibt, muss ich da einmal prüfen, woher ich diese Informationen jetzt bekommen kann.
